name: proassets
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Menggunakan rentang SDK yang lebih fleksibel

# Dependencies untuk proyek Anda
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

  # --- DEPENDENCY BARU UNTUK FIREBASE ---
  # firebase_core adalah pondasi untuk semua layanan Firebase
  firebase_core: ^2.32.0
  # firebase_auth untuk menangani autentikasi (login, register, dll.)
  firebase_auth: ^4.20.0
  # cloud_firestore untuk database NoSQL dari Firebase
  cloud_firestore: ^4.17.4

  google_sign_in: ^6.2.1 # <-- TAMBAHKAN BARIS INI

  # --- DEPENDENCY LAMA YANG DIPERTAHANKAN ---
  # Ikon-ikon gaya iOS
  cupertino_icons: ^1.0.8

  # --- DEPENDENCY LAMA YANG DIHAPUS ---
  # http: ^1.2.1 # Dihapus karena pemanggilan API digantikan oleh Firebase SDK

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0 # Versi lints yang lebih umum dan terbaru

# Konfigurasi spesifik untuk Flutter
flutter:
  uses-material-design: true

  # --- BAGIAN PENTING YANG DIPINDAHKAN DARI pubspec.yaml LAMA ---
  # Pastikan file font Anda berada di folder 'fonts' di root proyek
  fonts:
    - family: Josefin Sans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
    - family: Jost
      fonts:
        - asset: fonts/Jost-Regular.ttf