// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQ4e50_cLt9zvy6yqeayB16Svozs27hY',
    appId: '1:514863288530:web:fb9e2565d0707eec66dd0b',
    messagingSenderId: '514863288530',
    projectId: 'proasset-27031',
    authDomain: 'proasset-27031.firebaseapp.com',
    storageBucket: 'proasset-27031.firebasestorage.app',
    measurementId: 'G-FMG5E0HTS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe2_pi0fuJQEso0dyXmgCZxyYU1A6mCBM',
    appId: '1:514863288530:android:5e404241cf355b3b66dd0b',
    messagingSenderId: '514863288530',
    projectId: 'proasset-27031',
    storageBucket: 'proasset-27031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFy9rBo_7OZL9J5RZ0oaYWPfFYSS_PezM',
    appId: '1:514863288530:ios:1c619ffb2696b1a766dd0b',
    messagingSenderId: '514863288530',
    projectId: 'proasset-27031',
    storageBucket: 'proasset-27031.firebasestorage.app',
    iosBundleId: 'com.example.proassets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFy9rBo_7OZL9J5RZ0oaYWPfFYSS_PezM',
    appId: '1:514863288530:ios:1c619ffb2696b1a766dd0b',
    messagingSenderId: '514863288530',
    projectId: 'proasset-27031',
    storageBucket: 'proasset-27031.firebasestorage.app',
    iosBundleId: 'com.example.proassets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxQ4e50_cLt9zvy6yqeayB16Svozs27hY',
    appId: '1:514863288530:web:38ece7daf739039e66dd0b',
    messagingSenderId: '514863288530',
    projectId: 'proasset-27031',
    authDomain: 'proasset-27031.firebaseapp.com',
    storageBucket: 'proasset-27031.firebasestorage.app',
    measurementId: 'G-F41E2MWNXN',
  );
}
